@startuml c4-container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
HIDE_STEREOTYPE()
SHOW_PERSON_OUTLINE()

AddRelTag("invisivel", $textColor="white", $lineColor="white", $lineStyle = DashedLine())

Person(admin, "Persona")

System_Boundary(c1, "ST") {
    Container(cli, "Aplicativo CLI", "Linha de comandos", "Configuração e consulta")
    Container(gui, "ST", "API Spring Boot", "FHIR Terminology Service")
    ContainerDb(guicli, "Terminologias", "Códigos e índices", "Dados locais")
}

@enduml
