@startuml dominio

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class Conta {
    usuario
    senha
}

class Solução {
}

class Arquivo {
    nome
}

class Json {
}

class FSH {
}

class XML {
}

class Recurso {
}

class Terminologia {
}

class CodeSystem <<resource>> {
}

class ValueSet <<resource>> {
}

class ConceptMap <<resource>> {
}

class NamingSystem <<resource>> {
}

class StructureDefinition <<resource>> {
}

class Elemento {}
class Extensão {}

Terminologia -up-|> Recurso
StructureDefinition -left-|> Recurso

CodeSystem -up-|> Terminologia
ValueSet -up-|> Terminologia
ConceptMap -up-|> Terminologia
NamingSystem -up-|> Terminologia

Arquivo -right-> Recurso : "Registra\ninstância de"
Solução *-right-> Arquivo
Solução "1" -left-> Conta

XML -up-|> Arquivo
Json -up-|> Arquivo
FSH -up-|> Arquivo


Recurso -up-> Elemento
Recurso -up-> Formulário : Visualizado\npor
Elemento *-right-> "0..*" Extensão : Contém

Extensão -down-> StructureDefinition : Definida por\ninstância de

@enduml
