@startuml dominio

hide circle
hide methods
hide empty members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor #505050
}

class Conta {
    usuario
    senha
}

class Solução {
}

class Arquivo {
    nome
}

class Json {
}

class FSH {
}

class XML {
}

class Recurso {
}

class Terminologia {
}

class CodeSystem {
}

class ValueSet {
}

class ConceptMap {
}

class NamingSystem {
}

class StructureDefininition {
}

Terminologia -up-|> Recurso
StructureDefininition -up-|> Recurso
CodeSystem -up-|> Terminologia
ValueSet -up-|> Terminologia
ConceptMap -up-|> Terminologia
NamingSystem -up-|> Terminologia

Arquivo -right-> Recurso : "Registra\ninstância de"
Solução *-right-> Arquivo
Solução "1" -left-> Conta

XML -up-|> Arquivo
Json -up-|> Arquivo
FSH -up-|> Arquivo

@enduml
